org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-camol
addon_name=BlueMap Camol Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-camol-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=32265
accepted_jar_sha256=b107291040c1816e209929db37bc2871e25b9b7ab128ec2cc58f1cceaf47db53
